-- MySQL Script generated by MySQL Workbench
-- Thu Nov 20 18:36:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco-voebem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco-voebem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco-voebem` DEFAULT CHARACTER SET utf8 ;
USE `banco-voebem` ;

-- -----------------------------------------------------
-- Table `banco-voebem`.`passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-voebem`.`passageiro` (
  `id_passageiro` INT NOT NULL AUTO_INCREMENT,
  `nome_passageiro` VARCHAR(100) NOT NULL,
  `cpf_passageiro` CHAR(11) NULL,
  `telefone_passageiro` VARCHAR(20) NULL,
  `email_passageiro` VARCHAR(100) NULL,
  `endereco_passageiro` VARCHAR(100) NULL,
  `dt_nasc_passageiro` DATE NULL,
  PRIMARY KEY (`id_passageiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-voebem`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-voebem`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `telefone_funcionario` VARCHAR(20) NULL,
  `email_funcionario` VARCHAR(100) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-voebem`.`aviao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-voebem`.`aviao` (
  `id_aviao` INT NOT NULL AUTO_INCREMENT,
  `nome_aviao` VARCHAR(45) NOT NULL,
  `cor_aviao` VARCHAR(45) NULL,
  `ano_aviao` YEAR NULL,
  PRIMARY KEY (`id_aviao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-voebem`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-voebem`.`viagem` (
  `id_viagem` INT NOT NULL AUTO_INCREMENT,
  `partida_viagem` VARCHAR(100) NOT NULL,
  `destino_viagem` VARCHAR(100) NOT NULL,
  `data_viagem` DATE NULL,
  `valor_viagem` DECIMAL(10,2) NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  `passageiro_id_passageiro` INT NOT NULL,
  `aviao_id_aviao` INT NOT NULL,
  PRIMARY KEY (`id_viagem`, `funcionario_id_funcionario`, `passageiro_id_passageiro`, `aviao_id_aviao`),
  INDEX `fk_viagem_funcionario_idx` (`funcionario_id_funcionario` ASC) ,
  INDEX `fk_viagem_passageiro1_idx` (`passageiro_id_passageiro` ASC) ,
  INDEX `fk_viagem_aviao1_idx` (`aviao_id_aviao` ASC) ,
  CONSTRAINT `fk_viagem_funcionario`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `banco-voebem`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_passageiro1`
    FOREIGN KEY (`passageiro_id_passageiro`)
    REFERENCES `banco-voebem`.`passageiro` (`id_passageiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_aviao1`
    FOREIGN KEY (`aviao_id_aviao`)
    REFERENCES `banco-voebem`.`aviao` (`id_aviao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
